### ISSUE TITLE
Login code fails when username or password contains special characters

### ISSUE THREAD

**Issue by bennettBuckley** [CloudDataObject/JSDO#64]
Version 4.3.0-23

When a user's username or password contains certain special characters, login fails because form data is not properly encoded. the issue certainly exists when a "%" symbol is included, and likely exists in some form for other characters that have special functions in URLs.

The problem code is in src/progress.session.js, on line 1673:
`xhr.send("j_username=" + args.uname + "&j_password=" + args.pw + "&submit=Submit");`
The issue propagates to all the lib files as well.

The issue can be resolved by encoding the username and password as URI components:
`xhr.send("j_username=" + encodeURIComponent(args.uname) + "&j_password=" + encodeURIComponent(args.pw) + "&submit=Submit");`

To reproduce:

1. On web app back-end, configure a user that includes a "%" symbol as part of the password, using form-type login.
2. Attempt to log in with that user.

![image](https://cloud.githubusercontent.com/assets/8454993/26074647/89bd8c0c-3980-11e7-96d6-9ea50994b593.png)

**Comment by joshualan** [comment]
A fix has been added to encode usernames and passwords in form data properly as of release 4.4.
